### ISSUE TITLE
Float Problem

### ISSUE THREAD

**Issue by huseyinkozan** [pabigot/buffer-layout#16]
Hi,

I encounter a float problem. Is this normal ?

Code :
```node
var lo = require("buffer-layout");
var ds = lo.f32();
var b = Buffer.alloc(ds.span);
ds.encode(3.2, b);
var c = ds.decode(b);
console.log("b:", b);
console.log("3.2:", c);
```

Output:
```
b: <Buffer cd cc 4c 40>
3.2: 3.200000047683716
```

Env :
* Node : 6.9.1
* OS : Ubuntu 16.04 x86_64

**Comment by pabigot** [comment]
Yes.  3.2 can't be exactly represented.  The error in representation in 32-bit floating point representations shows up when the value is converted to Javascripts native 64-bit floating point value.

    > Buffer.from('cdcc4c40', 'hex').readFloatLE(0)
    3.200000047683716
