### ISSUE TITLE
C string inside fixed length array

### ISSUE THREAD

**Issue by mediumchris** [pabigot/buffer-layout#23]
I needed to decode C strings from inside a `char[4][40]`, eventually I created my own Layout class (which works) but feel I must have missed or misunderstood something. How can the below be achieved without the subclass?

    class SubBufferLayout extends Layout {

      constructor( elementLayout, span ) {
        super( span )
        this.elementLayout = elementLayout
      }

      decode( b, offset ) {
        let sub = b.slice( 0, offset + this.span )
        return this.elementLayout.decode( sub, offset )
      }

    }

And usage:

`lo.seq( new SubBufferLayout( lo.cstr(), 40 ), 4, 'blahBlah' )`

**Comment by pabigot** [comment]
I assume you want the JavaScript API to be an array of four Strings.  If so, the approach you've taken is probably optimal.  

The data structure you are working with is conceptually an array of four arrays of forty characters.  The natural layout for that would be:

    lo.seq(lo.seq(lo.u8(), 40), 4)

The [CString](http://pabigot.github.io/buffer-layout/module-Layout-CString.html) layout assumes an implicit length, based on presence of `NUL`.  For that you would use:

    lo.seq(lo.cstr(), 4)

What I understand you to want requires you to extract variable-length value from within a fixed-length layout used for each of the four elements in the outer sequence.  For this you would need [`getSpan`]( http://pabigot.github.io/buffer-layout/module-Layout-Layout.html#getSpan) on the element layout to return the fixed length when invoked from the container sequence to determine the element span, but the content-specific length when used to extract the value from the encoded element.

Your solution of a special layout is probably the best one.  Another would involve using a Union to overlay the two different element layouts, but a Union requires that the default layout have a fixed length (so it can skip over members without decoding them) while a non-default layout must have a property name and so would produce an array of objects.  Skipping the definition of a discriminator selecting the non-default variant you'd end up using something like:
```
const discr = new ConstantDiscriminator(0);
const str40 = lo.union(discr, lo.blob(40));
str40.addVariant(discr.tag, lo.cstr(), 's');
const lo3 = lo.seq(str40, 4);
```
and get back
```
[ { s: 'A' }, { s: 'BC' }, { s: 'CDE' }, { s: 'DEFG' } ]
```

**Comment by mediumchris** [comment]
That's helpful, thanks. The library is very useful so thanks for that too.

**Comment by pabigot** [comment]
You're welcome.
